spring:
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: raioxcape
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: America/Sao_Paulo
    locale: pt_BR
cors:
  mapping: /**
  allowed-methods: >
    GET,
    POST,
    PUT,
    PATCH,
    DELETE,
    HEAD,
    OPTIONS
  allowed-headers: >
    Access-Control-Allow-Origin,
    Access-Control-Request-Method,
    Access-Control-Allow-Headers,
    Access-Control-Expose-Headers,
    Authorization,
    Origin,
    Content-Type,
    Accept
  exposed-headers: >
    Access-Control-Allow-Origin,
    Access-Control-Request-Method,
    Access-Control-Allow-Headers,
    Authorization,
    Origin
  allow-credentials: false
  access-control-max-age: 3600
jogo:
  quantidade-enigmas-por-porta-caminho: 4
