spring:
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: raioxcape
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    time-zone: America/Sao_Paulo
    locale: pt_BR
